### ISSUE TITLE
A minor bug in the software gui

### ISSUE THREAD

**Issue by Akagi201** [SevenBits/Mac-Linux-USB-Loader#73] opened 2015-05-18 02:57 UTC
More options -> Show Project Website

will open  <http://sevenbits.github.io/projects/mlul.html> which is 404 not found.

**Comment by SevenBits** [comment] 2015-05-18 10:19
This is a duplicate of #70 and as I explained there, this is fixed in the upcoming 3.1. I am closing this issue, thanks for reporting.

**Closed by SevenBits** 2015-05-18 10:19 UTC
