### ISSUE TITLE
Not detect pendrive 16GB FAT

### ISSUE THREAD

**Issue by pedromoto4** [SevenBits/Mac-Linux-USB-Loader#29] opened 2013-08-17 01:20 UTC
hi I have OSX 10.7.5 and I am trying to use the program on my USB stick that is formatted with FAT.
The USB stick is 16GB. But the program does not recognize it. I'm doing something wrong or is it a bug?

**Comment by SevenBits** [comment] 2015-01-13 22:42
@pedromoto4 @dcosson Hi everyone, if your USB drive doesn't show up, please try formatting it again as FAT using Disk Utility. FAT formatters on other platforms may format your USB using a slightly different variant of the FAT32 file system which Mac Linux USB Loader is not compatible with.

**Comment by scerazy** [comment] 2015-02-26 20:32
Sadly ONLY FAT (and NOT FAT32) formatted USB is ever recognized. No matter what size the USB is
Why or why?

**Comment by SevenBits** [comment] 2015-02-26 20:49
@scerazy Formatting a USB as FAT32 on my Mac using Disk Utility works for me, and the resulting drive is detected by Mac Linux USB Loader. I can certainly look into this; perhaps there is a bug in the format detection code...

**Comment by scerazy** [comment] 2015-02-26 21:00
I have tested 1Gb, 2 Gb, 8G USB drives. Partitioned/Formatted on Mac & on Windows. The only combination that worked was just FAT. 

Anyway, doing it by hand is way easier, no need to use the program at all.
And testing it in Workstation 11 is also way quicker then rebooting Mac

I only would like actual examples of structure for:

**Comment by scerazy** [comment] 2015-02-26 21:04
.MLUL-Live-USB

as I can not find them on http://sevenbits.github.io/Enterprise/

Thanks

sc

**Comment by aschereT** [comment] 2015-06-17 05:02
Using OS X 10.10.2 on MId-2013 MBA. Couldn't see the 4GB Sandisk Cruzer Blade (FAT32), despite having formatted it several times

**Comment by SevenBits** [comment] 2015-06-18 22:39
@aschereT Unfortunately, I cannot reproduce this issue. Are you positive that it is formatted as FAT32?

**Comment by aschereT** [comment] 2015-06-19 18:46
I think might have been something with the paticular usb. I tried a HP x720w 16gb and it was detected. Albeit it can't find /casper/vmlinuz.ef

**Comment by SevenBits** [comment] 2015-06-21 17:56
@aschereT To you and anyone else with this issue, please help me address this issue by doing the following:

Run this command when the drive should be mounted (e.g inserted into the computer and recognized by the operating system):

    diskutil list

In addition, run this command and it should show activity when the USB drive is inserted:

    diskutil activity

Please share with me the result of both of these commands.

**Comment by aschereT** [comment] 2015-06-22 03:27
For the HP x720w:
diskutil list:
/dev/disk1
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *15.5 GB    disk1
   1:                 DOS_FAT_32 UBUNTU                  15.5 GB    disk1s1

diskutil activity, when plugging in
***DAIdle (no DADiskRef) Time=20150622-10:25:48.6846
***DiskPeek ('disk1s1') Time=20150622-10:25:55.7327
***DiskPeek ('disk1') Time=20150622-10:25:55.7333
***DiskMountApproval ('disk1s1', DAVolumePath = '<null>', DAVolumeKind = 'msdos', DAVolumeName = 'UBUNTU') Comment=Approving Time=20150622-10:25:55.7337
***DiskAppeared ('disk1', DAVolumePath = '<null>', DAVolumeKind = '<null>', DAVolumeName = '<null>') Time=20150622-10:25:55.7356
***DiskAppeared ('disk1s1', DAVolumePath = 'file:///Volumes/UBUNTU/', DAVolumeKind = 'msdos', DAVolumeName = 'UBUNTU') Time=20150622-10:25:55.8690
***DAIdle (no DADiskRef) Time=20150622-10:25:55.8693

**Comment by SevenBits** [comment] 2015-06-22 03:31
And this drive is not detected by Mac Linux USB Loader?

**Comment by aschereT** [comment] 2015-06-22 04:07
This one works fine. The broken one, the Cruzer Blade 4GB, I don't have with me.

**Comment by SevenBits** [comment] 2015-06-22 15:10
I need the data for the one that doesn't work. Otherwise, how can I fix the bug?

**Comment by aschereT** [comment] 2015-06-25 04:21
Sorry for the long wait,
the one not detected: (diskutil activity)
***DAIdle (no DADiskRef) Time=20150625-11:17:39.7655
***DiskPeek ('disk2s1') Time=20150625-11:17:44.4806
***DiskPeek ('disk2') Time=20150625-11:17:44.4815
***DiskMountApproval ('disk2s1', DAVolumePath = '<null>', DAVolumeKind = 'msdos', DAVolumeName = 'mystick') Comment=Approving Time=20150625-11:17:44.4824
***DiskAppeared ('disk2', DAVolumePath = '<null>', DAVolumeKind = '<null>', DAVolumeName = '<null>') Time=20150625-11:17:44.4848
***DiskAppeared ('disk2s1', DAVolumePath = 'file:///Volumes/mystick/', DAVolumeKind = 'msdos', DAVolumeName = 'mystick') Time=20150625-11:17:44.8058
***DAIdle (no DADiskRef) Time=20150625-11:17:44.8060

diskutil list:
/dev/disk2
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *4.0 GB     disk2
   1:                 DOS_FAT_32 mystick                 4.0 GB     disk2s1

again, 3.1cp2

**Comment by SevenBits** [comment] 2015-06-25 21:43
@aschereT Okay, thank you. I am actually going to send this to Apple as part of my ongoing bug report about this issue.

If you want a "debug mode", you can compile MLUL from source.

**Comment by TheDudealiasRobert** [comment] 2015-07-18 12:10
Dear Sevebits,
I can plug in an USB device which can be found by my Macbook Pro (2012) but which is not recognized by your program. It is the Sandisk Extreme USB 3.0 with 64GB (SDCZ80-064G).
Diskutil list echos the following:
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *64.0 GB    disk2
   1:                 DOS_FAT_32 OHNE TITEL              64.0 GB    disk2s1

diskutil activity:
***Begin monitoring DiskArbitration activity
***DiskAppeared ('disk2s1', DAVolumePath = 'file:///Volumes/OHNE%20TITEL/', DAVolumeKind = 'msdos', DAVolumeName = 'OHNE TITEL') Time=20150718-13:58:13.6686
***DiskAppeared ('disk2', DAVolumePath = '<null>', DAVolumeKind = '<null>', DAVolumeName = '<null>') Time=20150718-13:58:13.6691

I would like to read your comment.

**Comment by SevenBits** [comment] 2015-07-18 14:48
@TheDudealiasRobert I'm sending all of these issues to Apple. Hopefully they can give me some information as to what might be causing this.

**Comment by cems2** [comment] 2015-08-23 18:54
Hi, I'm having the same issue.  
platform: macbook core2duo
OS:  10.7.5
target: linux mint
I have tried this on 3 USB drives. one is a 4GB Imation,  one is a sandisk 16MB, the other is a hongkong mystery brand 128GB.  program runs fine and efi folder is there.  No error displayed.  but mac does not recognize these in its list of bootable disks.

here is the Diskutil activity for one of these (16GB sandisk usb2):
***DiskPeek ('disk2') Time=20150823-12:44:00.5199
***DiskMountApproval ('disk2', DAVolumePath = '<null>', DAVolumeKind = 'msdos', DAVolumeName = 'STRAUSS') Comment=Approving Time=20150823-12:44:00.5237
***DiskAppeared ('disk2', DAVolumePath = 'file://localhost/Volumes/STRAUSS/', DAVolumeKind = 'msdos', DAVolumeName = 'STRAUSS') Time=20150823-12:44:00.8877
***DAIdle (no DADiskRef) Time=20150823-12:44:00.8880

diskutil list
/dev/disk0
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *320.1 GB   disk0
   1:                        EFI                         209.7 MB   disk0s1
   2:                  Apple_HFS MacHD                   319.2 GB   disk0s2
   3:                 Apple_Boot Recovery HD             650.0 MB   disk0s3
/dev/disk1
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *3.9 GB     disk1
   1:                 DOS_FAT_32 SPARTICUS               3.9 GB     disk1s1
/dev/disk2
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:                            STRAUSS                *16.0 GB    disk2


and here's the output of disk activity when I push in the 4G drive (SPARTICUS)
***DiskPeek ('disk1') Time=20150823-12:53:29.4275
***DiskPeek ('disk1s1') Time=20150823-12:53:29.4539
***DiskAppeared ('disk1', DAVolumePath = '<null>', DAVolumeKind = '<null>', DAVolumeName = '<null>') Time=20150823-12:53:29.4557
***DiskMountApproval ('disk1s1', DAVolumePath = '<null>', DAVolumeKind = 'msdos', DAVolumeName = 'SPARTICUS') Comment=Approving Time=20150823-12:53:29.4567
***DiskAppeared ('disk1s1', DAVolumePath = 'file://localhost/Volumes/SPARTICUS/', DAVolumeKind = 'msdos', DAVolumeName = 'SPARTICUS') Time=20150823-12:53:29.7738
***DAIdle (no DADiskRef) Time=20150823-12:53:29.7748

list of files on the drive:

efi>boot>  (files)
boot.efi
boot.iso
bootX64.efi

**Comment by cems2** [comment] 2015-08-23 19:50
addendum:  I realized that for one of the drives I had not fomratted it with the MBR.  correcting this oversite did not fix the failure to boot to linux.  the drive is still not recognized in either the startup disk preference or at the boot time option.
here's the revised disk activity output

***DAIdle (no DADiskRef) Time=20150823-13:47:32.7403
***DiskPeek ('disk1') Time=20150823-13:47:39.6345
***DiskPeek ('disk1s1') Time=20150823-13:47:39.6801
***DiskAppeared ('disk1', DAVolumePath = '<null>', DAVolumeKind = '<null>', DAVolumeName = '<null>') Time=20150823-13:47:39.6926
***DiskAppeared ('disk1s1', DAVolumePath = '<null>', DAVolumeKind = 'msdos', DAVolumeName = 'SPARTICUS') Time=20150823-13:47:39.6933
***DiskMountApproval ('disk1s1', DAVolumePath = '<null>', DAVolumeKind = 'msdos', DAVolumeName = 'SPARTICUS') Comment=Approving Time=20150823-13:47:40.4268
***DiskDescriptionChanged ('disk1s1', DAVolumePath = 'file://localhost/Volumes/SPARTICUS/') Time=20150823-13:47:40.7578
***DAIdle (no DADiskRef) Time=20150823-13:47:40.7583

diskutil list
/dev/disk0
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *320.1 GB   disk0
   1:                        EFI                         209.7 MB   disk0s1
   2:                  Apple_HFS MacHD                   319.2 GB   disk0s2
   3:                 Apple_Boot Recovery HD             650.0 MB   disk0s3
/dev/disk1
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *3.9 GB     disk1
   1:                 DOS_FAT_32 SPARTICUS               3.9 GB     disk1s1
/dev/disk2
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *16.0 GB    disk2
   1:                 DOS_FAT_32 STRAUSS                 16.0 GB    disk2s1

**Comment by SevenBits** [comment] 2015-08-23 20:22
@cems2 Thanks, I'll make a note of the data.

**Comment by cems2** [comment] 2015-08-24 01:56
I’m wondering what would happen if I built this on a newer machine (using your v3 version) then tried to use it on my older core 2 duo running 10.75.   Is the machine it get’s built on need to be the machine that the live CD runs on.  I would imagine that at a minimum they both need to be 64 bit.  But are there any customization that are build-machine dependent?

I’m wondering if a newer 10.10 machine running the 3.0 version would build a better USB for the 10.7.5 machine.

> On Aug 23, 2015, at 2:22 PM, SevenBits <notifications@github.com> wrote:
> 
> @cems2 <https://github.com/cems2> Thanks, I'll make a note of the data.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/SevenBits/Mac-Linux-USB-Loader/issues/29#issuecomment-133921591>.
> 

Charlie Strauss
cems@me.com

**Comment by Marcool04** [comment] 2015-12-20 14:42
Hello,
I am also experiencing issues with a functional 16GB drive, brand new in fact, which is not showing up in MLUL.

    $ diskutil list
    /dev/disk1
       #:                       TYPE NAME                    SIZE       IDENTIFIER
       0:     FDisk_partition_scheme                        *16.0 GB    disk1
       1:                 DOS_FAT_32 UNTITLED                16.0 GB    disk1s1
And:

    $diskutil activity
    [Inserted drive at this point]
    ***DiskPeek ('disk1s1') Time=20151220-15:34:04.6299
    ***DiskPeek ('disk1') Time=20151220-15:34:04.6305
    ***DiskMountApproval ('disk1s1', DAVolumePath = '<null>', DAVolumeKind = 'msdos', DAVolumeName = 'UNTITLED') Comment=Approving Time=20151220-15:34:04.6313
    ***DiskAppeared ('disk1s1', DAVolumePath = 'file://localhost/Volumes/UNTITLED/', DAVolumeKind = 'msdos', DAVolumeName = 'UNTITLED') Time=20151220-15:34:04.9910
    ***DiskAppeared ('disk1', DAVolumePath = '<null>', DAVolumeKind = '<null>', DAVolumeName = '<null>') Time=20151220-15:34:04.9914

I also took a look at the system log while MLUL was working.
It starts up ok, find Enterprise. Then when I select an ISO it outputs this:

    20/12/15 15:36:22,431 Mac Linux USB Loader[23779]: Volume at / is not eligible. Type: hfs
    20/12/15 15:36:22,435 Mac Linux USB Loader[23779]: Detected eligible volume at /Volumes/UNTITLED. Type: msdos
Which seems good to me... but then the drive does not show up in MLUL, and the following messages are output by the kernel:

    20/12/15 15:36:22,000 kernel[0]: Sandbox: sandboxd(23794) deny mach-lookup com.apple.coresymbolicationd
    20/12/15 15:36:22,978 sandboxd[23794]: ([23779]) Mac Linux USB Lo(23779) deny mach-lookup com.apple.KernelExtensionServer
This doesn't look too good, but I can't decide if they would have anything to do with the drive not appearing...
Hope this helps.
Regards,
Mark.

**Comment by harshnarang8** [comment] 2016-03-11 08:23
Using MBP Retina 2015, OSX 10.11.3. Having the same problem, can't detect a Hard drive.
The Hard Drive is of size 1Tb, and Partitioned into 3 volumes.

diskutil list shows
`/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *121.3 GB   disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:          Apple_CoreStorage Macintosh HD            120.5 GB   disk0s2
   3:                 Apple_Boot Recovery HD             650.0 MB   disk0s3
/dev/disk1 (internal, virtual):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:                  Apple_HFS Macintosh HD           +120.1 GB   disk1
                                 Logical Volume on disk0s2
                                 E0E8DEE0-E6BF-43CD-AD56-40B31E2F9133
                                 Unlocked Encrypted
/dev/disk2 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *1.0 TB     disk2
   1:                        EFI EFI                     209.7 MB   disk2s1
   2:                  Apple_HFS My Passport             750.0 GB   disk2s2
   3:       Microsoft Basic Data HAHA FELLAS             249.7 GB   disk2s3`

diskutil activity :
`***Begin monitoring DiskArbitration activity
***DiskAppeared ('disk2s2', DAVolumePath = 'file:///Volumes/My%20Passport/', DAVolumeKind = 'hfs', DAVolumeName = 'My Passport') Time=20160311-13:51:54.0450
***DiskAppeared ('disk2s3', DAVolumePath = 'file:///Volumes/LINUX/', DAVolumeKind = 'msdos', DAVolumeName = 'LINUX') Time=20160311-13:51:54.0458
***DiskAppeared ('disk2s4', DAVolumePath = 'file:///Volumes/MYDRIVE/', DAVolumeKind = 'msdos', DAVolumeName = 'MYDRIVE') Time=20160311-13:51:54.0459
***DiskAppeared ('disk2s1', DAVolumePath = '<null>', DAVolumeKind = 'msdos', DAVolumeName = 'EFI') Time=20160311-13:51:54.0460
***DiskAppeared ('disk2', DAVolumePath = '<null>', DAVolumeKind = '<null>', DAVolumeName = '<null>') Time=20160311-13:51:54.0461
***DiskAppeared ((no BSD name), DAVolumePath = 'file:///home/', DAVolumeKind = 'autofs', DAVolumeName = '<null>') Time=20160311-13:51:54.0462
***DiskAppeared ((no BSD name), DAVolumePath = 'file:///net/', DAVolumeKind = 'autofs', DAVolumeName = '<null>') Time=20160311-13:51:54.0463
***DiskAppeared ('disk0', DAVolumePath = '<null>', DAVolumeKind = '<null>', DAVolumeName = '<null>') Time=20160311-13:51:54.0465
***DiskAppeared ('disk0s1', DAVolumePath = '<null>', DAVolumeKind = 'msdos', DAVolumeName = 'EFI') Time=20160311-13:51:54.0466
***DiskAppeared ('disk0s3', DAVolumePath = '<null>', DAVolumeKind = 'hfs', DAVolumeName = 'Recovery HD') Time=20160311-13:51:54.0468
***DiskAppeared ('disk0s2', DAVolumePath = '<null>', DAVolumeKind = '<null>', DAVolumeName = '<null>') Time=20160311-13:51:54.0469
***DiskAppeared ('disk1', DAVolumePath = 'file:///', DAVolumeKind = 'hfs', DAVolumeName = 'Macintosh HD') Time=20160311-13:51:54.0472
***DAIdle (no DADiskRef) Time=20160311-13:51:54.0473`

**Comment by SevenBits** [comment] 2016-03-11 15:27
@harshnarang8 Mac Linux USB Loader is programmed to ignore hard drives, since it is designed to only work with removable devices. However, a user has contributed the ability to install to hard drives, so that feature will be available soon.

**Comment by probablytom** [comment] 2016-04-11 14:06
Incase it helps, my 64gb drive remained undetected until I repartitioned and selected "Master Boot Record" as the partition map. Worked after that and I now have a fully functional Ubuntu installation. 

@cems2's earlier comment might suggest that this doesn't mean much, but I thought it worth mentioning.

**Comment by SevenBits** [comment] 2016-04-11 14:41
@probablytom Thanks for your suggestions, Tom.

**Comment by SevenBits** [comment] 2016-08-28 23:46
I am closing this thread for now, since there have been no new posts. Will re-open if necessary.

**Closed by SevenBits** 2016-08-28 23:46 UTC
Labels: bug
