### ISSUE TITLE
USB flash drive not seen

### ISSUE THREAD

**Issue by monikamatis** [SevenBits/Mac-Linux-USB-Loader#86] opened 2015-09-19 08:17 UTC
I tried Cruzer Edge 16GB drive to create a bootable usb stick for Ubuntu based distribution. All works nicely except for an important issue - there is no drive to choose from, despite the fact that the stick is mounted and working properly on the system.
System is Yosemite 10.10.5 run on a late 2014 Mac Mini

**Comment by SevenBits** [comment] 2015-09-19 20:52
What do you mean by:

> there is no drive to choose from, despite the fact that the stick is mounted and working properly on the system

Do you mean the USB doesn't show up in the boot manager?

**Comment by monikamatis** [comment] 2015-09-19 21:10
yes, exactly

**Comment by SevenBits** [comment] 2015-09-21 19:17
@monikamatis Can you please share the layout of files on your USB drive?

**Comment by SevenBits** [comment] 2015-10-24 18:23
Closing as this is a duplicate of #29.

**Closed by SevenBits** 2015-10-24 18:23 UTC
